require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*.rb

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

RSpec/NestedGroups:
  Max: 5
