language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - jruby-9.1.9.0

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
    - rvm: jruby-9.1.9.0
  fast_finish: true

cache:
  - bundler
  - directories:
    - /home/travis/.rvm/

notifications:
  email:
    on_success: change
